sonar.organization=mihir021
sonar.projectKey=mihir021_resume-maker-
sonar.sources=Python
sonar.tests=tests
sonar.python.version=3.11
sonar.python.coverage.reportPaths=coverage.xml
sonar.exclusions=**/node_modules/**,**/venv/**,**/__pycache__/**,**/.git/**,**/test.py,**/test_openai.py